del *.SchDoc.Zip		/s
del *.PcbDoc.Zip		/s
del *.SchLib.Zip		/s
del *.PcbLib.Zip		/s
del *.pcb.Zip			/s
del *.PrjPCB.Zip		/s
del *.pcbdoc_viewstate	/s
del *.SchDocPreview		/s
del *.PcbDocPreview		/s
del *.$$$Preview        /s
del *.LOG				/s